trainer: progressive_consistency_distillation
distribution_loss: progressive_consistency_distillation

generator_ckpt: checkpoints/bernini_v2v_prefix_init.pt
teacher_ckpt: checkpoints/bernini_v2v_prefix_init.pt
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size

v2v: true
load_raw_video: true
data_path: /apdcephfs/private_huitinglu/ReCo-Data/replace/replace_data_configs.json
base_video_folder: /apdcephfs/private_huitinglu/ReCo-Data
prompt_key: instruction_final_refine
src_key: src_video
num_raw_frames: 81
target_fps: 16
height: 480
width: 832

teacher_num_steps: 50
student_num_steps: 4
guidance_scale: 6.0
timestep_shift: 3.0
mixed_precision: true
gradient_checkpointing: true

sharding_strategy: hybrid_full
lr: 1.0e-06
beta1: 0.0
beta2: 0.999
weight_decay: 0.01
batch_size: 1
total_batch_size: 8
ema_weight: 0.99
ema_start_step: 200
log_iters: 200
gc_interval: 100
seed: 0

negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'

model_kwargs:
  timestep_shift: 3.0

wandb_host: WANDB_HOST
wandb_key: WANDB_KEY
wandb_entity: WANDB_ENTITY
wandb_project: WANDB_PROJECT
